name: myAction
concurrency:
    group: thEdenBbay
    cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

env:
    AZURE_RESOURCE_GROUP_NAME: bicep

permissions:
  id-token: write
  contents: read

defaults:
  run:
      shell: pwsh

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
        with:
          path: 'repo'
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{vars.ENTRA_CLIENT_ID}}
          tenant-id: ${{vars.ENTRA_TENANT_ID}}
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - name: Run linting and preflight validation
        env:
          AZURE_RESOURCE_GROUP_NAME: ${{env.AZURE_RESOURCE_GROUP_NAME}}
          AZURE_SUBSCRIPTION_ID: ${{vars.AZURE_SUBSCRIPTION_ID}}
          GITHUB_WORKFLOW_RUN_NUMBER: ${{github.run_number}}
        run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            $azureContex = Set-AzContext -Subscription $env:AZURE_SUBSCRIPTION_ID

            $testDeploymentParameters = @{
                'ResourceGroupName' = $env:AZURE_RESOURCE_GROUP_NAME
                'TemplateFile' = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'repo' -AdditionalChildPath @('deploy','main.bicep')
                'SkipTemplateParameterPrompt' = $true
                'TemplateParameterObject' = @{
                  'userAssignedIdentityName' = 'UAMI-zzz'
                }
                'DefaultProfile' = $azureContex
            }

            $testResults = Test-AzResourceGroupDeployment @testDeploymentParameters

            if ($testResults -ne '')
            {
              throw $testResults
            }

            Write-Information 'Preflight validation Completed successfuly'
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
        with:
          path: 'repo'
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{vars.ENTRA_CLIENT_ID}}
          tenant-id: ${{vars.ENTRA_TENANT_ID}}
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - name: Run what-if
        env:
          AZURE_RESOURCE_GROUP_NAME: ${{env.AZURE_RESOURCE_GROUP_NAME}}
          AZURE_SUBSCRIPTION_ID: ${{vars.AZURE_SUBSCRIPTION_ID}}
          GITHUB_WORKFLOW_RUN_NUMBER: ${{github.run_number}}
        run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            $azureContex = Set-AzContext -Subscription $env:AZURE_SUBSCRIPTION_ID

            $previewDeploymentParameters = @{
                'ResourceGroupName' = $env:AZURE_RESOURCE_GROUP_NAME
                'TemplateFile' = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'repo' -AdditionalChildPath @('deploy','main.bicep')
                'SkipTemplateParameterPrompt' = $true
                'TemplateParameterObject' = @{
                  'userAssignedIdentityName' = 'UAMI-zzz'
                }
                'DefaultProfile' = $azureContex
            }

            ($previewDeploymentResults = Get-AzResourceGroupDeploymentWhatIfResult @previewDeploymentParameters)

            Write-Information $previewDeploymentResults
  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: [preview]
    outputs:
      groupId: ${{ steps.deploy_main.outputs.groupId }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
        with:
          path: 'repo'
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{vars.ENTRA_CLIENT_ID}}
          tenant-id: ${{vars.ENTRA_TENANT_ID}}
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - name: Deploy to Azure
        id: deploy_main
        env:
          AZURE_RESOURCE_GROUP_NAME: ${{env.AZURE_RESOURCE_GROUP_NAME}}
          AZURE_SUBSCRIPTION_ID: ${{vars.AZURE_SUBSCRIPTION_ID}}
          GITHUB_WORKFLOW_RUN_NUMBER: ${{github.run_number}}
        run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            $azureContex = Set-AzContext -Subscription $env:AZURE_SUBSCRIPTION_ID

            $deploymentParameters = @{
                'Name' = "$($env:GITHUB_WORKFLOW_RUN_NUMBER)_$(Get-Date -Format FileDateTimeUniversal)"
                'ResourceGroupName' = $env:AZURE_RESOURCE_GROUP_NAME
                'TemplateFile' = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'repo' -AdditionalChildPath @('deploy','main.bicep')
                'Force' = $true
                'SkipTemplateParameterPrompt' = $true
                'TemplateParameterObject' = @{
                  'userAssignedIdentityName' = 'UAMI-zzz'
                }
                'DefaultProfile' = $azureContex
            }

            ($deploymentResults = New-AzResourceGroupDeployment @deploymentParameters)

            Write-Information $deploymentResults

            "groupId=$($deploymentResults.Outputs.groupId.Value)" >> $env:GITHUB_OUTPUT
  smoke-test:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{vars.ENTRA_CLIENT_ID}}
          tenant-id: ${{vars.ENTRA_TENANT_ID}}
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - name: Validate group existance
        env:
          groupId: ${{needs.deploy.outputs.groupId}}
        run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            Get-AzADGroup -ObjectId $env:groupId -DefaultProfile $azureContex
