name: myAction
concurrency:
    group: thEdenBbay
    cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

env:
  MAX_MODULE_VESRION: '7.9999.9999'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/reusable/lint.yml
    with:
      bicepPath: './deploy/main.bicep'
  # Deploy to the test environment.
  deploy-test:
    uses: ./.github/workflows/reusable/deploy.yml
    needs: [lint]
    with:
      environmentType: test
      AZURE_RESOURCE_GROUP_NAME: bicep-test
      ENTRA_CLIENT_ID: ${{ vars.ENTRA_CLIENT_ID_TEST }}
      ENTRA_TENANT_ID: ${{ vars.ENTRA_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID_TEST }}
      MAX_MODULE_VESRION: ${{ env.MAX_MODULE_VESRION }}
      TemplateParameterFilePath: './deploy/main.test.bicepparam'
  deploy-prod:
      uses: ./.github/workflows/reusable/deploy.yml
      needs: [deploy-test]
      with:
        environmentType: prod
        AZURE_RESOURCE_GROUP_NAME: bicep-prod
        ENTRA_CLIENT_ID: ${{ vars.ENTRA_CLIENT_ID_PROD }}
        ENTRA_TENANT_ID: ${{ vars.ENTRA_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID_PROD }}
        MAX_MODULE_VESRION: ${{ env.MAX_MODULE_VESRION }}
        TemplateParameterFilePath: './deploy/main.prod.bicepparam'