name: myAction
concurrency:
    group: thEdenBbay
    cancel-in-progress: false

on: [workflow_dispatch]

env:
    AZURE_RESOURCEGROUP_NAME: bicep

permissions:
  id-token: write
  contents: read

defaults:
  run:
      shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          # client-id: ${{secrets.AZURE_CLIENT_ID}}
          # tenant-id: ${{vars.TENANT_ID}}
          # subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          client-id: '5a23adef-6f6e-459e-8921-62cd1f128ab7'
          tenant-id: '464edfaa-792d-4ff8-84f0-94290a8360ae'
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - name: Deploy to Azure
        id: deploy_main
        env:
          AZURE_RESOURCEGROUP_NAME: ${{env.AZURE_RESOURCEGROUP_NAME}}
          AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          GITHUB_WORKFLOW_RUNNUMBER: ${{github.run_number}}
        run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            Write-Information "Set the Azure subscription to [$env:AZURE_SUBSCRIPTION_ID]"
            Select-AzSubscription -SubscriptionId $env:AZURE_SUBSCRIPTION_ID

            $deployment = @{
                'Name' = $env:GITHUB_WORKFLOW_RUNNUMBER
                'TemplateFile' = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'deploy' -AdditionalChildPath @('main.bicep')
                'Force' = $true
                'SkipTemplateParameterPrompt' = $true
                'TemplateParameterObject' = @{
                  'userAssignedIdentityName' = 'UAMI-zzz'
                }
            }

            ($results = New-AzResourceGroupDeployment @deployment -ResourceGroupName $env:AZURE_RESOURCEGROUP_NAME)

            "groupId=$($results.Outputs.groupId.Value)" >> $env:GITHUB_OUTPUT
